name: Python Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest # Ensure pytest is installed

    - name: Run pytest and save output
      id: pytest
      run: |
        pytest | tee pytest-result.txt
      # Continue on error so the next step can create an issue
      continue-on-error: true

    - name: Create Issue on Test Failure
      if: steps.pytest.outcome == 'failure'
      uses: peter-evans/create-issue-from-file@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Unit Test Failures on main branch"
        content-filepath: pytest-result.txt
        labels: jules
        assignees: ${{ github.actor }}
