name: Python Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write        # still required for non-fork PRs

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    - name: Run pytest and save output
      id: pytest
      run: |
        set -o pipefail
        pytest | tee pytest-result.txt
      continue-on-error: true

    - name: Create Issue on Test Failure
      if: steps.pytest.outcome == 'failure'
      uses: peter-evans/create-issue-from-file@v5
      with:
        token: ${{ secrets.PAT_TOKEN }}        # ← use a PAT here
        title: "Unit Test Failures on main branch"
        content-filepath: pytest-result.txt
        labels: jules
        assignees: ${{ github.actor }}
      continue-on-error: true               # prevents exit code 2 if creation still fails
